# Generated by Django 3.2.3 on 2021-07-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artista', models.CharField(max_length=99)),
                ('duracion', models.IntegerField()),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disco')),
            ],
        ),
    ]
