# Generated by Django 3.2.3 on 2021-07-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='nombre',
            field=models.CharField(default='', max_length=99),
        ),
    ]
